FP7 - AI project setup
SupportAI-Project/SupportAI-Model-AI pull request #1
Opened 2024-05-26 19:18 UTC by TomerMiz10

Jira Task:
[https://mssplinter10-1711638164183.atlassian.net/jira/software/projects/FP/boards/6?selectedIssue=FP-7](url)

added:

- OpenAI Service:
  - Connects to OpenAI API.
  - Makes a call to the Chat Completions API.
  - An asynchronous function named `getTroubleshootingSteps` that takes a `supportNote` parameter of type string. It uses the OpenAI API to generate troubleshooting steps based on the provided support note. 
  - Uses gpt-3.5-turbo Model.
  
 - Controller:
  - Sends that POST request with the prompt, as a Promise.
  
 - Module:
  - Bundles up the previous two, and exports OpenAIService.
  
 - App Service:
  - Logs the response from the API and returns the content of the first choice in the response as a string..

2024-05-26 20:29 UTC, nitzanto requested changes

2024-05-26 20:29 UTC, nitzanto commented on test/app.controller.spec.ts
This is a unit test that should be within the app resource folder not within the e2e tests folder.

2024-05-26 20:29 UTC, nitzanto commented on src/services/app.service.ts
> +    return 'Hello World!' + word + result;
This is only a healthcheck why is the logic of openai service is injected here?

2024-05-26 20:29 UTC, nitzanto commented on src/modules/openai.module.ts
This should be within it's own resource folder 'openai'.

2024-05-26 20:29 UTC, nitzanto commented on src/modules/app.module.ts
app should be within an 'app' resource folder aswell.

2024-05-26 20:29 UTC, nitzanto commented on src/main.ts
Why was the port switched to 3002 if you've set the docker compose to interlink the ports from 3002 to 3000.
This should be 3000

2024-05-26 20:29 UTC, nitzanto commented on src/controllers/openai.controller.ts
Change to 'getGuide'.

2024-05-26 20:29 UTC, nitzanto commented on src/services/openai.service.ts
> +    private openai: OpenAIApi;
make this private readonly

2024-05-26 20:29 UTC, nitzanto commented on src/services/openai.service.ts
> +dotenv.config();
Delete dotenv there's no use for it. You can natively use process.env

2024-05-26 20:29 UTC, nitzanto commented on src/services/openai.service.ts
> +                { role: 'user', content: supportNote }
The content and prompt itself should be in a lib folder as a constant of read only.

2024-05-26 20:29 UTC, nitzanto commented on src/services/openai.service.ts
> +        console.log(response.choices[0]);
Remove console.log

2024-05-26 20:29 UTC, nitzanto commented on test/openai.service.spec.ts
This unit test should be within the openai resource folder. If there's no unit test here then you can just remove it.

2024-05-26 20:29 UTC, nitzanto commented on src/controllers/openai.controller.ts
> +    async getTroubleshootingSteps(@Body("supportNote") prompt: string): Promise<string> {
Why there's no use of DTO here? Also this isn't a prompt its a chat conversation summary.

2024-05-26 20:29 UTC, nitzanto commented on src/services/openai.service.ts
> +    async getTroubleshootingSteps(supportNote: string): Promise<string> {
Should be a DTO

2024-05-26 20:30 UTC, nitzanto commented
Looks into the right direction. There are some stuff that needs to be changed.

2024-05-27 10:37 UTC, TomerMiz10 commented on src/modules/openai.module.ts
it is either we divide the folders into "controllers" ,"services" , "modules".....
OR we divide them into "openai" , "app" , "auth" ......
it is very confusing all this reviews, suggestions and little comments.

2024-05-27 10:59 UTC, nitzanto requested changes

2024-05-27 10:59 UTC, nitzanto commented on src/dto/openai.dto.ts
The DTO itself should receive the chat conversation not the configuration for OpenAI

2024-05-27 10:59 UTC, nitzanto commented on src/controllers/app.controller.ts
Why is this in the app controller? You duplicated the code here and in open ai controller.

2024-05-27 10:59 UTC, nitzanto commented on src/lib/constans.ts
Create a folder called openai inside lib and put the constants.ts there

2024-05-27 10:59 UTC, nitzanto commented on src/main.ts
> +dotenv.config();
Delete this.

2024-05-27 10:59 UTC, nitzanto commented on src/services/openai.service.ts
> +        // };
Remove commented code.

2024-05-27 10:59 UTC, nitzanto commented on src/services/app.service.ts
> +  }
This shouldnt be here. OpenAI and App are different resources.

2024-05-27 11:00 UTC, nitzanto requested changes

2024-05-27 11:00 UTC, nitzanto commented on src/controllers/app.controller.ts
> +}
Why is this in the app controller? You duplicated the code here and in open ai controller.

2024-05-29 15:44 UTC, TomerMiz10 commented on src/controllers/app.controller.ts
> +}
removed. done

2024-05-29 15:44 UTC, TomerMiz10 commented on src/lib/constans.ts
changed. done

2024-05-29 15:45 UTC, TomerMiz10 commented on src/main.ts
> +dotenv.config();
done

2024-05-29 20:01 UTC, nitzanto requested changes
Some stuff needs to be changed.

Also make sure the folder is structured like this:

/src
│
├── /app                 
│   ├── app.module.ts
│   └── main.ts
│
├── /lib
│   ├── openai
│   └── interfaces
│   └── data
│
├── /openai                 
│   ├── /controllers         
│   │   └── openai.controller.ts
│   │
│   ├── /dto         
│   │   └── openai.dto.ts
│   │
│   ├── /services           
│   │   └── openai.service.ts
│   │
│   │
│   └── openai.module.ts     
│

2024-05-29 20:01 UTC, nitzanto commented on src/lib/openai/constants.ts
> +};
Should be of type ConversationMessages.

`export const MESSAGES: { ConversationMessages } `

ConversationMessages : Record<string, string>

Also since MESSAGES is data, I recommend putting this in a JSON file in a data folder.

2024-05-29 20:01 UTC, nitzanto commented on src/dto/openai.dto.ts
You can create a types folder and move the types to there. lib/types or lib/interfaces.

message should be instead ChatMessage with pascal cases.

2024-05-29 20:01 UTC, nitzanto commented on src/dto/openai.dto.ts
> +}
The model shouldn't be given in the API request. It should have a default value which you already created before. 

export const GPT_MODEL: string = 'gpt-3.5-turbo'

In addition add to the api request DTO a chat id. We want a reference for the chat that the open ai is going to summarize and create a guide from

2024-05-29 20:01 UTC, nitzanto commented on src/controllers/openai.controller.ts
get-guide should return instead of a string some sort of JSON. Create a GuideResponseDTO then return Promise<GuideResponseDTO> instead of Promise<string>

2024-05-29 20:01 UTC, nitzanto commented on src/main.ts
> +dotenv.config();
Delete this dotenv.

If you want to use env variables then use NestJS's ConfigModule & ConfigService.

2024-05-29 20:01 UTC, nitzanto commented on src/services/openai.service.ts
> +}
* Change function name from getConversation to formatConversation since the function is formatting into a specific format. Also instead of messagesConvo it should be ConversationMessages.

* Change from `import * as constants from "src/lib/openai/constants" `  to this:
`import { GPT_MODEL, MESSAGES } from "src/lib/openai/constants";`
 Try adding index.ts within lib folder to export files in this way.

* There should be more of a separation of concerns, getGuide calls this.formatConversation -> getGuide calls this.generateResponse(formattedConverstaion) -> return guide

* Add more logging & error handling to know if the request was successful or edge cases if there was an error. Try using NestJS's Logger for this. Logger.info, Logger.error etc..

2024-05-30 14:17 UTC, TomerMiz10 commented on src/lib/openai/constants.ts
> +};
moved openai related files into `openai` folder.
made a `ConversationMessages` type, read the `messages `from the JSON file and sent saved in `MESSAGES`.

2024-05-30 14:51 UTC, TomerMiz10 commented on src/main.ts
> +dotenv.config();
done

2024-06-08 14:54 UTC, TomerMiz10 commented on src/services/openai.service.ts
> +}
Due to the quota limits, I managed to send a request, but not getting a response. The quotas error tells us the request was processed and managed to reach the API.
This is a BASIC DEMO interface for communicating with the OpenAI API. Of course, we will refactor this to be cleaner, more organized, and fully interactionable with the Backend. In addition, we will train the model with conversations and prompt engineering.
But for now, this is a start.

2024-07-04 17:27 UTC, nitzanto approved these changes
Awesome.

2024-07-04 17:27 UTC, merged